# Generated by Django 3.2.5 on 2021-08-01 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(max_length=255)),
                ('birth_date', models.DateTimeField(verbose_name='date published')),
                ('mobile', models.CharField(max_length=255)),
                ('current_city', models.CharField(max_length=255)),
                ('friends', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('like', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.facebook')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('page_type', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountapp.facebook')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(max_length=255)),
                ('moderator', models.CharField(max_length=255)),
                ('members', models.IntegerField(default=0)),
                ('privacy', models.CharField(max_length=50)),
                ('visible', models.CharField(max_length=50)),
                ('group_type', models.CharField(max_length=50)),
                ('rules', models.CharField(max_length=1000)),
                ('admin', models.ManyToManyField(blank=True, null=True, to='accountapp.Facebook')),
            ],
        ),
    ]
