# Generated by Django 3.0.14 on 2021-08-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='birth_date',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='facebook',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
