# Generated by Django 3.0.14 on 2021-08-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20210809_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
