# Generated by Django 3.0.14 on 2021-08-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
