# Generated by Django 3.0.14 on 2021-08-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_auto_20210813_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook',
            name='current_city',
        ),
    ]
