# Generated by Django 3.2.6 on 2021-08-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0008_auto_20210819_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='station_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('station_id', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('station_seq', models.IntegerField(default=0)),
                ('exist_bus', models.CharField(max_length=10)),
                ('latitude', models.IntegerField(default=0)),
            ],
        ),
    ]
