# Generated by Django 3.2.7 on 2021-11-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0009_station_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.IntegerField()),
            ],
        ),
    ]
